### ISSUE TITLE
query regarding the completeness of your code  

### ISSUE THREAD

**Issue by akhila-suresh-rao** [v-spirin/MRESim#1]
Hi ! 

I read about MRESim from a paper and thought I would check it out. I see that the code is still being updated. Is this project complete, i.e. can I download it and use it now ?

**Comment by v-spirin** [comment]
Hi Akhila,

You are welcome to download and use it as it is! The project is "complete" in the sense that it will compile and run fine "out of the box". However, it is also a constant work in progress; I am actively using it for my PhD research, and so I am constantly modifying it, adding features to it and resolving issues.

There should be no major issues with the simulation framework itself, such as moving, sensing, path planning and communication. There could be some issues with individual exploration strategies. I would recommend starting with the "Frontier-based: Unconstrained, return when done" exploration strategy to get used to the simulator, as that exploration strategy is the simplest.

By the way, could you please let me know which paper you found out about MRESim from, and also what your research is in? I am just curious.

Regards,

Victor

**Comment by akhila-suresh-rao** [comment]
Hi Victor,

Thank you for your response and your advice. I am a masters student working
on multi-agent SLAM for my thesis. I first encountered MRESim in a paper by
Tuna et.al, "The effects of exploration strategies and communication models
on the performance of cooperative exploration". I am interested in
exploring the collective performance of exploration strategies and
opportunistic communication in multi-agent exploration. I wanted to use
some exploration strategies already implemented in java as a first step.
What is your field of work for your PhD ?

Regards
Akhila

**Comment by akhila-suresh-rao** [comment]
Hi Victor,

I read through the paper "MRESim, a multi-robot exploration simulator for the rescue simulation league" and played around with the simulator's exploration strategies and am very interested in using it for my master thesis work. Is there any sort of documentation for the simulator ? I wanted to understand all the visual information the simulator is providing (ex: what are the thick green lines that are occasionally formed between robots, what do white yellow and green regions on the map mean). I would be grateful if you could suggest a way I can get more indept knowledge about the implementations used in the simulator. Thank you !!    

Regards
Akhila

**Comment by akhila-suresh-rao** [comment]
I am also curious to know if you are assuming that the map merging process is done with known initial relative positions of the robots. And is the merging process error free ? If needed I will read the code, but I just wanted to know if there is an easier way of doing this :D

**Comment by v-spirin** [comment]
Localization, mapping as well as map merging are assumed to be perfect in the simulator - so there is no noise/errors. It should be reasonably easy to add noise to the robot localization, however. But adding noise to the laserscanner and errors to SLAM and map merging would be difficult - I would say that if those errors are important to the experiments, using USARSim/ROS with the code of one of the RoboCup Rescue Virtual Robots league team, or Player/Stage could be a better option.
